### ISSUE TITLE
Mutual recursion is only broken inside tests 

### ISSUE THREAD

**Issue by catb0t** [presidentbeef/brat#22]
I'm not familiar with Brat's internals, so I can't debug it any further. But, I am not sure if you noticed this, and maybe it helps debugging.

The code is pretty much directly taken from `test-examples.brat`, but with the testy parts commented out. 

If you run this code as-is, it prints `true true`

```lua
#*
include :assert

setup name: :x {
  test "mutual recursion" {
*#
    female = null #yes, this is necessary

    male = { n |
      true? n == 0
      { 0 }
      { n - female male(n - 1) }
    }

    female = { n |
      true? n == 0
      { 1 }
      { n - male female(n - 1 ) }
    }

    p ([1, 1, 2, 2, 3, 3, 4, 5, 5, 6, 6, 7, 8, 8, 9, 9, 10, 11, 11, 12, 13] == {
      0.to(20).map! { n | female n }
    }())

    p ([0, 0, 1, 2, 2, 3, 4, 4, 5, 6, 6, 7, 7, 8, 9, 9, 10, 11, 11, 12, 12] == {
      0.to(20).map! { n | male n }
    }())

#*
    assert_equal [1, 1, 2, 2, 3, 3, 4, 5, 5, 6, 6, 7, 8, 8, 9, 9, 10, 11, 11, 12, 13] {
      0.to(20).map! { n | female n }
    }

    assert_equal [0, 0, 1, 2, 2, 3, 4, 4, 5, 6, 6, 7, 7, 8, 9, 9, 10, 11, 11, 12, 12] {
      0.to(20).map! { n | male n }
    }
  }
}
*#
```

But if you uncomment the test framework, then it prints 

```
Test failure(s):

	1. 'mutual recursion': mrec.lua:888: attempt to call local '_temp6' (a table value)
```

So, user code can use mutual recursion as long as it isn't inside `setup` /  `test`?

**Comment by presidentbeef** [comment]
Hi @catb0t -

Thank you for your interest :)

There are certainly cases in which mutual recursion works fine.

The problem is there is an optimization that Brat does where it lifts function definitions out into a global namespace, in some circumstances.

For example, in this code:

```
f = {
  [1 2 3 4].map { a |
    a * 2
  }
}
```

The inner function 

```
{ a |
    a * 2
}
```
will be lifted out so it will only be created once instead of every time `f` is called.

Right now there is a bug where this "lifting" breaks when a variable is re-assigned after the function is created.

**Comment by catb0t** [comment]
I understand now. You can close this if you'd like.
